DDona.HeavyReports.Web/Controllers/HomeController.cs
using DDona.HeavyReports.RV.DataSets.dsReportPessoasTableAdapters;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDona.HeavyReports.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public FileResult PDF()
        {
            string ReportName = "Relatorio_Pessoas.pdf";
            byte[] ReportBytes = RenderReport("PDF");

            return File(ReportBytes, "aplication/pdf", ReportName);
        }

        public FileResult Excel()
        {
            string ReportName = "Relatorio_Pessoas.xls";
            byte[] ReportBytes = RenderReport("Excel");

            return File(ReportBytes, "application/excel", ReportName);
        }

        private byte[] RenderReport(string Type)
        {
            LocalReport LocalReport = new LocalReport();
            PersonTableAdapter PersonTableAdapter = new PersonTableAdapter();
            byte[] ReportBytes = null;
            Stopwatch sw = new Stopwatch();

            LocalReport.ReportPath = Server.MapPath("~/Reports/ReportPessoas.rdlc");

            sw.Start();
            LocalReport.DataSources.Add(new ReportDataSource("dsPessoas", (object)PersonTableAdapter.GetData()));
            sw.Stop();

            Debug.WriteLine("{0} - Carregando a Query e passando pra objetos", sw.Elapsed);

            sw.Restart();
            ReportBytes = LocalReport.Render(Type);
            sw.Stop();

            Debug.WriteLine("{0} - Montando o PDF", sw.Elapsed);

            return ReportBytes;
        }
    }
}

DDona.HeavyReports.Web/Controllers/VendasController.cs
using DDona.HeavyReports.RV.DataSets.dsReportVendasTableAdapters;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDona.HeavyReports.Web.Controllers
{
    public class VendasController : Controller
    {
        public FileResult PDF()
        {
            string ReportName = "Relatorio_Vendas.pdf";
            byte[] ReportBytes = RenderReport("PDF");

            return File(ReportBytes, "aplication/pdf", ReportName);
        }

        public FileResult Excel()
        {
            string ReportName = "Relatorio_Vendas.xls";
            byte[] ReportBytes = RenderReport("Excel");

            return File(ReportBytes, "application/excel", ReportName);
        }

        private byte[] RenderReport(string Type)
        {
            LocalReport LocalReport = new LocalReport();
            VendasTableAdapter VendasTableAdapter = new VendasTableAdapter();
            byte[] ReportBytes = null;
            Stopwatch sw = new Stopwatch();

            LocalReport.ReportPath = Server.MapPath("~/Reports/ReportVendas.rdlc");

            sw.Start();
            LocalReport.DataSources.Add(new ReportDataSource("dsVendas", (object)VendasTableAdapter.GetData()));
            sw.Stop();

            Debug.WriteLine("{0} - Carregando a Query e passando pra objetos", sw.Elapsed);

            sw.Restart();
            ReportBytes = LocalReport.Render(Type);
            sw.Stop();

            Debug.WriteLine("{0} - Montando o PDF", sw.Elapsed);

            return ReportBytes;
        }
    }
}

DDona.HeavyReports.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Relatórios</h1>
    <p>
        Clique numa opção do menu para testar
    </p>
</div>

DDona.HeavyReports.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Report PDF", "PDF", "Home")</li>
                    <li>@Html.ActionLink("Report Excel", "Excel", "Home")</li>
                    <li>@Html.ActionLink("Report Vendas PDF", "PDF", "Vendas")</li>
                    <li>@Html.ActionLink("Report Vendas Excel", "Excel", "Vendas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>